### ISSUE TITLE
DispatchDraw 不执行

### ISSUE THREAD

**Issue by Liaoer** [haolange/InfinityFoliage#2]
请问。if (boundsVisible[i] == 0) { continue; }    boundsVisible[0]一直为  0，是没有写完的吗？

**Comment by haolange** [comment]
对地形Go右键Entity Action执行Build Grass。不要直接AddComponent。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Mr.Liao ***@***.***&gt;
发送时间: 2022年1月18日 20:29
收件人: haolange/InfinityFoliage ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [haolange/InfinityFoliage] DispatchDraw 不执行 (Issue #2)





 
请问。if (boundsVisible[i] == 0) { continue; }    boundsVisible[0]一直为  0，是没有写完的吗？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
